EntityFrameworkCoreApp/Controllers/OgrenciController.cs
using EntityFrameworkApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkCoreApp.Controllers
{
    public class OgrenciController: Controller
    {
        private readonly DataContext _context;

        public OgrenciController(DataContext context) //OgrenciController constructor'u 
        {
            _context = context; //Bu kullanım ile DataContext sınıfına ait tüm entity'lere erşim sağlayabiliriz.
        }

        public async Task<IActionResult> Index()
        {
            var ogrenciler = await _context.Ogrenciler.ToListAsync();
            return View(ogrenciler);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Ogrenci model) //Database işlemleri genellikle async (asenkron) olur
        {
            _context.Add(model);
            await _context.SaveChangesAsync(); //Yapılan değişikler asenkron olarak yapılır ve kaydedilir
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var ogr = await _context
                            .Ogrenciler
                            .Include(o => o.KursKayitlari) //Öncelikle bu kısımda Include metodu ile ilişkili tabloları dahil ediyoruz
                            .ThenInclude(o => o.Kurs) //Daha sonra ThenInclude metodu ile ilişkili tabloların içindeki diğer ilişkili tablolarını dahil ediyoruz
                            .FirstOrDefaultAsync(o => o.Id == id);
            if(ogr == null)
            {
                return NotFound();
            }
            return View(ogr);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Formu açan kişiye özgü üretilen token'ın geçerliliğini kontrol eder ve sadece o token'a sahip kişinin o sayfaya erişimine izin verir.
        public async Task<IActionResult> Edit(int id, Ogrenci model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch(DbUpdateConcurrencyException) //Aynı anda kayıt güncellemesi yapılırken günceleme yapılan kayıdın silindiği durumda oluşabilecek hatalar
                {
                    if(!_context.Ogrenciler.Any(o => o.Id == id)) //Database'de kayıt yoksa true değeri döndürür
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ogr = await _context.Ogrenciler.FindAsync(id);
            if (ogr == null)
            {
                return NotFound();
            }
            return View("DeleteConfirm", ogr);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id, Ogrenci model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Ogrenciler.Remove(model);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    return NotFound();
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

EntityFrameworkCoreApp/Views/Ogrenci/Create.cshtml
@model Ogrenci
<h2>Öğrenci Kayıt</h2>
<hr />
<form asp-controller="Ogrenci" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Ad" class="form-label">Öğrenci Adı</label>
        <input asp-for="Ad" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Soyad" class="form-label">Öğrenci Soyadı</label>
        <input asp-for="Soyad" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Öğrenci Emaili</label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Öğrenci Telefonu</label>
        <input asp-for="Telefon" class="form-control" />
    </div>

    <button class="btn btn-secondary">Kaydet</button>
</form>

EntityFrameworkCoreApp/Views/Ogrenci/DeleteConfirm.cshtml
@model Ogrenci

<div>
    <p>
        @Model.Ad @Model.Soyad isimli öğrenciyi silmek istediğinize emin misiniz?
        <form asp-action="Delete" method="post">
            <input type="hidden" name="id" value="@Model.Id" />
            <button type="submit" class="btn btn-success">Evet</button>
            <a href="Index" class="btn btn-danger">Hayır</a>
        </form>
    </p>
</div>

EntityFrameworkCoreApp/Views/Ogrenci/Edit.cshtml
@model Ogrenci

<h2>Öğrenci Bilgi Güncelleme</h2>
<hr />
<div class="row">
    <div class="col-8">
        <form asp-controller="Ogrenci" asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="mb-3">
                <label asp-for="Ad" class="form-label">Öğrenci Adı</label>
                <input asp-for="Ad" class="form-control" />
            </div>
            <div class="mb-3">
                <label asp-for="Soyad" class="form-label">Öğrenci Soyadı</label>
                <input asp-for="Soyad" class="form-control" />
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Öğrenci Emaili</label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label">Öğrenci Telefonu</label>
                <input asp-for="Telefon" class="form-control" />
            </div>

            <button class="btn btn-secondary">Kaydet</button>
        </form>
    </div>
    <div class="col-4">
        <h4>Kurslar</h4>
        <hr />
        <ul>
            @foreach (var item in @Model.KursKayitlari)
            {
                <li>@item.Kurs.Baslik</li>
            }
        </ul>
    </div>
</div>

EntityFrameworkCoreApp/Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>

<h2>Öğrenciler Listesi</h2>
<a asp-controller="Ogrenci" asp-action="Create" class="btn btn-primary">Kayıt Ekle</a>
<hr />
<table class="table table-bordered">
    <thead>
        <tr>
            @*<th>Öğrenci Id</th>
            <th>Öğrenci Ad</th>
            <th>Öğrenci Soyad</th> bu şekilde elle yazmak yerine direk olarak ilgili yerden isimleri çekebiliriz*@
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.Id)</th>
            <th>@Html.DisplayNameFor(m => m.Ad)</th>
            <th>@Html.DisplayNameFor(m => m.Soyad)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var info in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => info.Id)</td>
                <td>@Html.DisplayFor(modelItem => info.Ad)</td>
                <td>@Html.DisplayFor(modelItem => info.Soyad)</td>
                <td>
                    <a asp-controller="Ogrenci" asp-action="Edit" asp-route-id="@info.Id" class="btn btn-sm btn-success">Edit</a>
                    <a asp-controller="Ogrenci" asp-action="Delete" asp-route-id="@info.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>