EntityFrameworkCoreApp/Controllers/KursController.cs
using EntityFrameworkApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkCoreApp.Controllers
{
    public class KursController : Controller
    {
        private readonly DataContext _context;

        public KursController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var kurs = await _context.Kurslar.ToListAsync();
            return View(kurs);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Kurs model)
        {
            _context.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var kurs = await _context
                .Kurslar
                .Include(k => k.KursKayitlari)
                .ThenInclude(k => k.Ogrenci)
                .FirstOrDefaultAsync(m => m.KursId == id);
            if (kurs == null)
            {
                return NotFound();
            }
            return View(kurs);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Kurs kurs)
        {
            if (id != kurs.KursId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kurs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!_context.Kurslar.Any(k => k.KursId == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                    
                }
                return RedirectToAction("Index"); 
            }
            return View(kurs);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null) 
            {
                return NotFound(); 
            }
            var kurs = await _context.Kurslar.FindAsync(id);
            if (kurs == null)
            {
                return NotFound();
            }
            return View("DeleteConfirm", kurs);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var kurs = await _context.Kurslar.FindAsync(id);
            if (kurs == null)
            {
                return NotFound();
            }

            try
            {
                _context.Kurslar.Remove(kurs);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException)
            {
                return RedirectToAction("Index", new { id = id, saveChangesError = true });
            }
        }

    }
}

EntityFrameworkCoreApp/Views/Kurs/Create.cshtml
@model Kurs

<form asp-controller="Kurs" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Baslik" class="form-label">Kurs Adı</label>
        <input asp-for="Baslik" class="form-control" />
    </div>
    <button class="btn btn-secondary">Kaydet</button>
</form>

EntityFrameworkCoreApp/Views/Kurs/DeleteConfirm.cshtml
@model Kurs

<div>
    <p>
        @Model.Baslik isimli kursu silmek istediğinize emin misiniz?
        <form asp-action="Delete" method="post">
            <input type="hidden" name="id" value="@Model.KursId" />
            <button type="submit" class="btn btn-danger">Evet</button>
            <a asp-action="Index" class="btn btn-success">Hayır</a>
        </form>
    </p>
</div>

EntityFrameworkCoreApp/Views/Kurs/Edit.cshtml
@model Kurs

<h2>Kurs Güncelleme</h2>
<hr />

<div class="row">
    <div class="col-8">
        <form asp-controller="Kurs" asp-action="Edit" method="post">
            <input type="hidden" asp-for="KursId" />
            <div class="mb-3">
                <label asp-for="Baslik" class="form-label">Kurs Adı</label>
                <input asp-for="Baslik" class="form-control" />
            </div>
            <button class="btn btn-secondary">Kaydet</button>
        </form>
    </div>
    <div class="col-4">
        <h4>Öğrenciler</h4>
        <hr />
        @foreach(var item in @Model.KursKayitlari)
        {
            <li>@item.Ogrenci.AdSoyad</li>
        }
    </div>
</div>

EntityFrameworkCoreApp/Views/Kurs/Index.cshtml
@model IEnumerable<Kurs>

<h2>Kurslar Listesi</h2>
<a asp-controller="Kurs" asp-action="Create" class="btn btn-primary">Kurs Ekle</a>
<hr />
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(k => k.KursId)</th>
            <th>@Html.DisplayNameFor(k => k.Baslik)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var kurs in Model){
            <tr>
                <td>@Html.DisplayFor(modelItem => kurs.KursId)</td>
                <td>@Html.DisplayFor(modelItem => kurs.Baslik)</td>
                <td>
                    <a asp-controller="Kurs" asp-action="Edit" asp-route-id="@kurs.KursId" class="btn btn-sm btn-success">Edit</a>
                    <a asp-controller="Kurs" asp-action="Delete" asp-route-id="@kurs.KursId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>