MeetingApp/Models/MeetingInfo.cs
namespace MeetingApp.Models
{
    public class MeetingInfo{
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberOfPeople { get; set; }
    }
}

MeetingApp/Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository
    {
        private static List<UserInfo> _userInfo = new List<UserInfo>();

        static Repository()
        {
            _userInfo.Add(new UserInfo { Id = 1, Name = "Ali", Phone = "1234567890", Email = "abc@gmail.com", WillAttend = true });
            _userInfo.Add(new UserInfo { Id = 2, Name = "Veli", Phone = "2574865514", Email = "asd@gmail.com", WillAttend = false });
            _userInfo.Add(new UserInfo { Id = 3, Name = "Deli", Phone = "7895462130", Email = "zxc@gmail.com", WillAttend = true });
        }

        public static List<UserInfo> Users
        {
            get
            {
                return _userInfo;
            }
        }

        public static void AddUser(UserInfo user)
        {
            user.Id = Users.Count + 1;
            _userInfo.Add(user);
        }

        public static UserInfo? GetById(int id)
        {
            return _userInfo.FirstOrDefault(i => i.Id == id);
        }
    }
}

MeetingApp/Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models{
    public class UserInfo{
        public int Id { get; set; }
        [Required (ErrorMessage = "Ad alanı zorunludur.")]
        public string? Name { get; set; }
        [Required (ErrorMessage = "Telefon alanı zorunludur.")]
        [Phone]
        public string? Phone { get; set; }
        [Required (ErrorMessage = "Email alanı zorunludur.")]
        [EmailAddress]
        public string? Email { get; set; }
        [Required (ErrorMessage = "Katılım durumunuzu seçmeniz gereklidir.")]
        public bool? WillAttend { get; set; }
    }
}

MeetingApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;

namespace MeetingApp.Controllers{
    public class HomeController: Controller{
        // localhost/home
        public IActionResult Index(){
            int saat = DateTime.Now.Hour;
            
            ViewData["Selamlama"] = saat > 12 ? "İyi Günler" : "Günaydın";
            var katilimci = Repository.Users.Where(info => info.WillAttend == true).Count();

            var meetingInfo = new MeetingInfo() {
                Id = 1,
                Location = "İzmir Abc Kongre Merkezi",
                Date = new DateTime(2024,03,07, 08, 43, 0),
                NumberOfPeople = katilimci

            };

            return View(meetingInfo);

            /* 
            var selamlama = saat > 12 ? "İyi Günler" : "Günaydın";
            return View(model: selamlama); gönderdiğimiz değerin bir model olduğunu belirtmemiz gerekir yoksa View olarak algılanır. cshtml dosyası olmadığından proje çöker. Gönerdiğimiz modeli kullanacağımız dizinde en üst satırda model tag'i ile belirmemiz gereklidir. Bu işlemler ViewBag ile de yapılabilir.*/
        }
    }
}

MeetingApp/Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
        //Aşağıdaki tanımladığımız Action Metotlarının defaultu HttpGet'tir. Özel olarak belirtmediğimiz sürece server bu şekilde algılar. [HttpGet] yazmasak bile server bunun Get isteği olduğunu algılar.
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Apply(){
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model){ //Formdan gelen verileri UserInfo modeline bind eder. Normelde burada tek tek string name, string phone vs. şeklinde alırdık. Ama model binding sayesinde bu işlemi yapmamıza gerek kalmaz.
            
            if (ModelState.IsValid){
                Repository.AddUser(model);
                ViewBag.UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
                return View("Thanks", model);
            }
            else{
                return View(model);
            }
        }

        public IActionResult List(){
            return View(Repository.Users);
        }

        public IActionResult Details(int id){
            return View(Repository.GetById(id));
        }
    }
}

MeetingApp/Views/Home/Index.cshtml
@model MeetingInfo
@{
    ViewBag.Title = "Toplantı Başvuru";
    Layout = "_Layout2";
}
<main class="text-center">
    <h1 class="h4">@ViewData["Selamlama"]</h1>
    <h2>Toplantı katılım durumunuzu bildiriniz</h2>

    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Toplantı Lokasyonu:
                @Model.Location
            </li>
            <li class="list-group-item">
                Tarih:
                @Model.Date.ToString("dd/MM/yyyy HH:mm:ss")
            </li>
            <!--@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") date bilgisini stringe çevirip format bilgisini veriyoruz.-->
            <li class="list-group-item">
                Katılımcı Sayısı:
                @Model.NumberOfPeople
            </li>
        </ul>
    </div>
    
    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap</a>
</main>

MeetingApp/Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Formu";
    Layout = "_Layout";
}

<h1 class="h4">Toplantı Katılım Formu</h1>
<form method="Post" action=""> <!--Post isteği-->
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Ad Soyad*</label>
        <span id="nameValidation" asp-validation-for="Name" class="text-danger"></span>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Telefon*</label>
        <span id="phoneValidation" asp-validation-for="Phone" class="text-danger"></span>
        <input asp-for="Phone" class="form-control"> 
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email*</label>
        <span id="emailValidation" id="nameValidation" asp-validation-for="Email" class="text-danger"></span>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Katılım Durumu*</label>
        <span id="willAttendValidation" asp-validation-for="WillAttend" class="text-danger"></span>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seçiniz</option>
            <option value="true">Evet</option>
            <option value="false">Hayır</option>
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

<!--Model binding yapmak için sadece asp-for kullanmamız gerekmez. label içerisindeki for ile select içerisindeki id değerleri aynı olduğu sürece model bindig geçerli olacaktır. Ör:
<div class="mb-3">
    <label for="Email" class="form-label">Email</label>
    <input type="email" name="Email" id="Email" class="form-control">
</div>
-->

MeetingApp/Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Detayı";
}

<table class="table table-striped table-bordered">
    @{
        var className = Model.WillAttend == true ? "table-success" : "table-danger";
        var katilim = Model.WillAttend == true ? "Katılıyor" : "Katılmıyor";
    }
    <thead class="thead-dark">
        <tr>
            <th scope="col">Özellik</th>
            <th scope="col">Değer</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>İsim</td>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <td>Telefon</td>
            <td>@Model.Phone</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>@Model.Email</td>
        </tr>
        <tr class="@className">
            <td>Katılım Durumu</td>
            <td>
                @katilim
            </td>
        </tr>
    </tbody>
</table>
<div class="d-flex justify-content-center">
    <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>
</div>

MeetingApp/Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "Toplantı Katılım Listesi";
    Layout = "_Layout";
}

<main class="text-center">
    <h1 class="h4">Toplantı Katılım Listesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durumu</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                var className = user.WillAttend == true ? "table-success" : "table-danger";
                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@(user.WillAttend == true ? "Evet" : "Hayır")</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</main>

MeetingApp/Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Durumu";
    Layout = "_Layout";
}

<main class="text-center">
    <h1 class="h4">Başvuru Durumu</h1>
    
    @if(Model.WillAttend == true)
    {
        <p>Teşekkürler @Model.Name, toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>
    }
    else
    {
        <p>@Model.Name toplantıya katılmadığınız için üzgünüz.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Toplantıya Katıl</a>
    }
</main>

MeetingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/styles.css" />
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-primary text-white p-2 text-center">
        <a href="/home/index" style="color: white; text-decoration: none;">MeetingApp</a>
    </div>
    <div class="container mt-3">
        <div class="col-lg-6 mx-auto">
            <div class="card">
                <div class="card-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>

MeetingApp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="col-lg-6 mx-auto text-center">
            <div class="card">
                <div class="card-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>